### ISSUE TITLE
Negative sensor temperature rolls over

### ISSUE THREAD

**Issue by svde** [vekexasia/comfoair-esp32#10]
The outside temperature is negative this evening, but it's reporting 6553.5 Celsius. I guess the value rolled over.

![image](https://user-images.githubusercontent.com/572598/142934543-5fb71446-2387-4553-aba9-e3a92fb1744c.jpeg)

From the Zehnder app:
![image](https://user-images.githubusercontent.com/572598/142934560-9cc5888d-5aa1-4f9b-a57b-de21b7be962e.jpeg)

**Comment by svde** [comment]
Implemented a workaround in node-red:

if( temp > 3276.7 ) {
  temp = temp - 6553.6;
}

**Comment by sodre90** [comment]
Hi, here is my PR to fix it: https://github.com/vekexasia/comfoair-esp32/pull/12
