### ISSUE TITLE
Esp getting into hanging state after 1-3 days neither sending or receiving data.

### ISSUE THREAD

**Issue by Erestes** [vekexasia/comfoair-esp32#17]
First of all thanks for the great work on this, works flawlessly with a small but.
My ESP hangs every 1,2,3 days and I need o shut down the unit and enable it back again to restore readings and control. I got the power supplied from the recu, my friend has a separate power via phone charger and it works for him without any issues. Any ideas what may be causing the issues in my case?

**Comment by vekexasia** [comment]
Hey, you're not the first one to tell me such issue. Unfortunately my esp32 is running stable since months now. Not a single time I had to powercycle it. 

What board are you using? How distant is the WiFi AP from the ESP32?

**Comment by Erestes** [comment]
I'm using ESP-WROOM-32
Distance between AP - ESP ca 7-8m through two walls, signal readings on the router = Medium but okay
I have another ESP for voltage/current readings which is bit furhter away and works without issues. I would remove the wifi signal from the equation.
What I haven't done and what I will check next time when it happens is whether the ESP is responding to pings while in hang state. 
I wonder if a periodic restart on ESP (for example at midnight) would help, but still wouldn't know what piece of code should be added and where.

**Comment by Erestes** [comment]
Interestingly since I posted this issue the ESP didn't crash so far :)
