### ISSUE TITLE
Option Box Connection Error

### ISSUE THREAD

**Issue by atomic339** [vekexasia/comfoair-esp32#18]
Hi, everything is working good. But I get error "option box connection error". I have to reconnect everything and error disappears but after few hours I get it again.
All commands from mqtt work good, even error appears.

**Comment by vekexasia** [comment]
I think the id of the device might conflict to the option box? Did you get this sorted?

**Comment by atomic339** [comment]
In my case it was a 2 problems:
- DC-DC converter (I changed to micro usb power supply and works good)
- after wifi lost esp32 can't connect again (someone post here "wifi loop command" - I compiled with this loop and works good)

After this works stable and great
