### ISSUE TITLE
sendCommand

### ISSUE THREAD

**Issue by ktomi88** [vekexasia/comfoair-esp32#2]
Hello,
 My question is about your sendCommand routine, which seems to send the same message twice with a 1 sec delay inbetween.
I found that sending only once is sufficient, but you have to make sure that you are sending right after a message has been received from the unit. This ensures that the unit is listening for incoming messages and there will be no collision on the bus when the unit is preparing or trying to send the next message. Do you mean is this right?

Best regards,
 Tamas

**Comment by vekexasia** [comment]
hey @ktomi88 i don't recall why i send twice. It's prob due to what you mentioned.
