### ISSUE TITLE
New configuration for mqtt 2022.12.0

### ISSUE THREAD

**Issue by atomic339** [vekexasia/comfoair-esp32#24]
![Screenshot_20220910-232922](https://user-images.githubusercontent.com/102626830/189502458-58159e26-270e-4646-848a-849545128ff8.jpg)

Do you make a new configuration or the old one will work?

**Comment by vekexasia** [comment]
I did change mine. I might commit a new version

**Comment by atomic339** [comment]
If you can it will be great

**Comment by atomic339** [comment]
Can you help me with this changes?
Put this to my config but sensors don't work:
mqtt:
  sensor:
    # Consumption
    - name: "VMC Power Current"
      state_topic: "comfoair/power_consumption_current"
      unit_of_measurement: W
    - name: "VMC Total Energy Saving"
      state_topic: "comfoair/ah_ytd"
      unit_of_measurement: Wh

# FAns
    - name: "VMC Exhaust Fan Speed"
      state_topic: "comfoair/exhaust_fan_speed"
      unit_of_measurement: rpm
    - name: "VMC Supply Fan Speed"
      state_topic: "comfoair/supply_fan_speed"
      unit_of_measurement: rpm
    - name: "VMC Exhaust Fan Duty"
      state_topic: "comfoair/exhaust_fan_duty"
      unit_of_measurement: rpm
    - name: "VMC Supply Fan Duty"
      state_topic: "comfoair/supply_fan_duty"
      unit_of_measurement: rpm
    - name: "VMC Supply Fan User Speed"
      state_topic: "comfoair/fan_speed"

  # FLOW
    - name: "VMC Exhaust   Fan Flow"
      state_topic: "comfoair/exhaust_fan_flow"
      unit_of_measurement: "m³/h"
    - name: "VMC Supply Fan Flow"
      state_topic: "comfoair/supply_fan_flow"
      unit_of_measurement: "m³/h"

# TEMPS
    - name: "VMC Outdoor Air Temperature"
      state_topic: "comfoair/outdoor_air_temp"
      unit_of_measurement: "°C"
    - name: "VMC Exhaust Air Temperature"
      state_topic: "comfoair/exhaust_air_temp"
      unit_of_measurement: "°C"
    - name: "VMC Extract Air Temperature"
      state_topic: "comfoair/extract_air_temp"
      unit_of_measurement: "°C"
    - name: "VMC Post Heater Temp Before"
      state_topic: "comfoair/post_heater_temp_before"
      unit_of_measurement: "°C"
    - name: "VMC Post Heater Temp After"
      state_topic: "comfoair/post_heater_temp_after"
      unit_of_measurement: "°C"

# Humidity
    - name: "VMC Outdoor Air Humidity"
      state_topic: "comfoair/outdoor_air_humidity"
      unit_of_measurement: "%"
    - name: "VMC Exhaust Air Humidity"
      state_topic: "comfoair/exhaust_air_humidity"
      unit_of_measurement: "%"
    - name: "VMC Extract Air Humidity"
      state_topic: "comfoair/extract_air_humidity"
      unit_of_measurement: "%"
    - name: "VMC Supply Air Humidity"
      state_topic: "comfoair/supply_air_humidity"
      unit_of_measurement: "%"

**Comment by atomic339** [comment]
Ok, it was a problem with my board. Works good
