### ISSUE TITLE
info installazione software 

### ISSUE THREAD

**Issue by mattiabrunello5** [vekexasia/comfoair-esp32#25]
Ciao Andrea,
per l'installazione software nell'ESP32 come procedo e con quali file della repo

grazie

**Comment by tobiaranz** [comment]
Ciao Andrea,
se non sei ancora riuscito devi utilizzare VScode con plugin platformio.
Scarica tutta la repository e apri l'intera cartella con platformio.
Dovrai aggiungere o modificare i dati come SSID PW e credenziali del broker mqtt nei file appositi.
