### ISSUE TITLE
Esp32 set ventilation leve 3 after reconeection

### ISSUE THREAD

**Issue by atomic339** [vekexasia/comfoair-esp32#28]
I have problem with occasionally drop wifi or mqtt connection. After auto reconnect esp set ventilation level to 3.
Is it depends on some test commands or?
Is there option to force send ventilation level 1 after reconnect?

Is there any option to connect esp32 with ethernet to get more stable connection?

**Comment by atomic339** [comment]
Any idea, please?

**Comment by Bokitoshopper** [comment]
I see the same, I disabled the debugging code (with #undef DEBUG) but it still seems to happens.
