### ISSUE TITLE
How to install in the Raspberry Home assistant?

### ISSUE THREAD

**Issue by Niki206cc** [vekexasia/comfoair-esp32#3]
Hi, i'm a newbie of HA and Raspberry and i hope to help other users newbie like me with this question. 

I downloaded comfoair-esp32-master.zip, unpacked and copied and pasted all files in custom_components/comfoair-esp32-master folder inside my Home Assistant Raspberry.

Is that the correct way? Should i have to add something in my configuration.yaml?

Thanks

**Comment by vekexasia** [comment]
Hey no. That is not the correct way. you need to check docs/ folder for haconfig and then check the yaml files.
