### ISSUE TITLE
Project compilation problems

### ISSUE THREAD

**Issue by MichalAug** [vekexasia/comfoair-esp32#32]
Dear All,
I have a problem compiling a project. After many hours I have reached the stage that I am getting an error related to the missing secrets.h file. But when I add it in the src folder, I get a double variable declaration error. What am I doing wrong? What should it look like? Please help :)
<img width="1107" alt="Zrzut ekranu 2022-10-3 o 00 02 30" src="https://user-images.githubusercontent.com/104733541/193479751-dfcb9bbf-5a44-4562-8f4d-0c7154a6afe1.png">

**Comment by MichalAug** [comment]
When I put this in secrets.h
const char* WIFI_SSID = "123";
const char* WIFI_PASS = "123";
const char* MQTT_USER = "mqttuser";
const char* MQTT_PASS = "mqtt pass";
const char* MQTT_PREFIX = "comfoair";
const char* MQTT_HOST = "192.168.2.100";
const char* MQTT_PORT = "6060";

I got:
src/comfoair/comfoair.cpp: In member function 'void comfoair::ComfoAir::setup()':
src/comfoair/comfoair.cpp:20:58: error: expected ')' before string constant
 #define subscribe(command) mqtt->subscribeTo(MQTT_PREFIX "/commands/" command, [this](char const * _1,uint8_t const * _2, int _3) { \

**Comment by jakubko186** [comment]
did you fix it?

**Comment by SkullboyNL** [comment]
Look at issue [#9](https://github.com/vekexasia/comfoair-esp32/issues/9)

**Comment by vekexasia** [comment]
You can just use esphome component now :)
