### ISSUE TITLE
No MQTT

### ISSUE THREAD

**Issue by Obelixje** [vekexasia/comfoair-esp32#35]
Hi,

There is no MQTT traffic coming from the esp32.
Is there a way to check logging on the ESP32?

When connecting to the IP of the ESP32 directly I only see possibility to upload files.

**Comment by mikka2** [comment]
You can check if ESP32 is sending data by connecting to MQTT broker that you set and check for incoming messages.

**Comment by Obelixje** [comment]
There are no incoming messages on the broker.

Do we ONLY expect messages when there is data coming in from Comfoair?
I am asking this because I may have blew up the Can tranceiver.

Or do we expect messages always when ESP is on the wifi. (Even when comfoair is not yet connected)?

**Comment by gsabbe** [comment]
In my experience messages are sent as they are received and decoded from
the comfoair.
Also the comfoair seems to only send data as it changes. So it took two
hours for all my variables to be set in Home Assistant.
One amelioration would be to send a status message every 60 seconds or so
just to say "I'm online".

**Comment by Obelixje** [comment]
ok,
thanks.
My first impression was that the Can tranciever is defect. It could be the case that I have to wait some hours for the first message..
Thanks for your help'

**Comment by gsabbe** [comment]
Things like fan speed would change rather quickly and are the first
messages I saw coming in. Can you connect your laptop to the ESP and open
the arduino console?
This way you'd see the message coming in, and perhaps triple check your
MQTT settings. (I managed to mess up the port and password when setting it
up the first time :))
I also blew up my ESP32 because I didn't tune the DC-DC step down to 3.3V
from the 12V set at the factory. The CAN module didn't care about the over
voltage thankfully.
Late night projects are always fun.

**Comment by Obelixje** [comment]
LOL

Same thing happened to me, also blew up the ESP32 because of the 12v...
I did triple test the incoming voltage (+/-), but did not check the outcoming voltage. So on my first connection I blew up the esp32, and an errormessage of the Comfoair.

I am going to connect the esp32 to Arduino, and see if something happens.

**Comment by gsabbe** [comment]
My comfoairq actually shutdown completely with my mistake, rather scary.
But it came back to life after unplugging/replugging the power.
The ESP 5V pin is a lot more tolerant and accepts unregulated 5-12V. But
the 3.3V wants regulated 3.3V and nothing else.

**Comment by Obelixje** [comment]
Is is working, the schedule was not correct.
![image](https://user-images.githubusercontent.com/83656588/202706870-a7305719-61fb-4f88-a0c6-a6ebeae305ee.png)

CanH and CANL were switched....

**Comment by Obelixje** [comment]
@gsabbe 
Thanks for your help this morning?
Do you have a good dashboard (yaml) that you can share?

**Comment by Obelixje** [comment]
All solved. Wiring issue....
