### ISSUE TITLE
Project finished

### ISSUE THREAD

**Issue by Obelixje** [vekexasia/comfoair-esp32#42]
I have finished my project. All does work as expected.
I am very happy with the result. Many thanks to @vekexasia and all who answered my many questions.

![open](https://user-images.githubusercontent.com/83656588/210245656-5a4d9aed-bade-499c-a167-acba9eaddccf.jpg)
![closed](https://user-images.githubusercontent.com/83656588/210245663-4c29ded1-4926-4e43-81c9-12edfb58dc38.jpg)
![UI](https://user-images.githubusercontent.com/83656588/210245668-e5606e2d-de7c-47ba-aa52-e74921f2633c.JPG)

**Comment by lskuba** [comment]
@Obelixje could you please share information about how to configure your dashboard? I am using ESP home version and  I am missing actions to e.g. change fan speed.
