### ISSUE TITLE
ComfoAir 70

### ISSUE THREAD

**Issue by JBN164** [vekexasia/comfoair-esp32#53]
Does this project also work with a ComfoAir70. 

It doesn't support the LAN C Adapter but works with a RF + Connect box. 

Connection via Bus is available (A,B, + and -). 

![image](https://github.com/vekexasia/comfoair-esp32/assets/132005901/e1dc6d8a-5b5d-4863-a93a-3919f59b671e)

![image](https://github.com/vekexasia/comfoair-esp32/assets/132005901/6fc3ac85-fb9c-486f-aa6e-9a27769a2ce8)

**Comment by vekexasia** [comment]
Unfortunately I can't answer that question. It looks like there is a can interface.

![image](https://github.com/vekexasia/comfoair-esp32/assets/200523/12869f2a-2d13-49b7-8949-411ba50a373c)

But if and on which extent this project would work it's unknown.

**Comment by vekexasia** [comment]
Were u able to test it out?

**Comment by vekexasia** [comment]
Hey @JBN164 any news?

**Comment by JBN164** [comment]
@vekexasia 
No I didn't test it and have no further informations

**Comment by vekexasia** [comment]
Ok, can I close the issue?
