### ISSUE TITLE
comfoair ESP32 - MQTT supported in ESPhome?

### ISSUE THREAD

**Issue by tudstudent** [vekexasia/comfoair-esp32#59]
Sorry, searching did not supply an answer.
I see there is a discrepancy in commit dates between the mqtt tree and the normal tree.
Furthermore, normal tree is esphome enabled, cannot find if mqtt tree can be used the same?

Additionally, I was searching for mqtt config details in esphome, also no luck so far.

Would you mind clarifying these details (or point in the right direction)

**Comment by fuatakgun** [comment]
esphome version does not require mqtt because it is directly connecting with home assistant using home assistant components.

**Comment by vekexasia** [comment]
Hey you can hook mqtt through home assistant if needed pushing data as soon
as ha receives it

**Comment by tudstudent** [comment]
Correct, have that already.
But it depends on HA.
Ideally would be to have it pushed to MQTT and then picked up by whatever UI/Tool I want.
(If HA is down for whatever reason the stable MQTT remains online and therefore data collection unaffected)

**Comment by vekexasia** [comment]
@tudstudent sorry for late response. you can use mqtt component and publish everything there if you want.
