### ISSUE TITLE
_builtin.h:36:10: fatal error: freertos/FreeRTOS.h: 

### ISSUE THREAD

**Issue by HAUSER3** [vekexasia/comfoair-esp32#61]
INFO ESPHome 2023.10.6
INFO Reading configuration /config/esphome/comfoair.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing comfoair (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Library Manager: Installing SPI @ 2.0.0
Warning! Could not find the package with 'SPI @ 2.0.0' requirements for your system 'linux_x86_64'
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
|-- can_common @ 0.3.0+sha.07605a2
|-- ESP32_CAN @ 0.2.5+sha.0fb9878
Compiling .pioenvs/comfoair/src/esphome/components/comfoair/comfoair.cpp.o
Compiling .pioenvs/comfoair/src/esphome/components/esp8266/gpio.cpp.o
Compiling .pioenvs/comfoair/src/esphome/components/esp8266/preferences.cpp.o
Compiling .pioenvs/comfoair/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
In file included from .piolibdeps/comfoair/esp32_can/src/esp32_can.h:1,
                 from src/esphome/components/comfoair/comfoair.h:2,
                 from src/esphome/components/comfoair/comfoair.cpp:1:
.piolibdeps/comfoair/esp32_can/src/esp32_can_builtin.h:36:10: fatal error: freertos/FreeRTOS.h: No such file or directory
   36 | #include "freertos/FreeRTOS.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/comfoair/src/esphome/components/comfoair/comfoair.cpp.o] Error 1
========================== [FAILED] Took 1.87 seconds ==========================

**Comment by vekexasia** [comment]
I cannot replicate.
