### ISSUE TITLE
Wrong units

### ISSUE THREAD

**Issue by pyzimmer** [vekexasia/comfoair-esp32#62]
Hello,
Thanks a lot for your job ! I use it for 2 years !
There are wrong units since your MQTT version : avoid heatind and cooling should be in Kwh, not Wh :

https://github.com/vekexasia/comfoair-esp32/blame/c0a6ce86d21b86724e2f58828678d477c8b6f70f/components/comfoair/__init__.py#L46

    "avoided_heating_actual": {"unit": "W", "PDO": 213, "CONV": ComfoNumConvs.UINT16, "div": 100},
    "avoided_heating_ytd":    {"unit": "kWh", "PDO": 214, "CONV": ComfoNumConvs.UINT16},
    "avoided_heating_total":  {"unit": "kWh", "PDO": 215, "CONV": ComfoNumConvs.UINT16},

    "avoided_cooling_actual": {"unit": "W", "PDO": 216, "CONV": ComfoNumConvs.UINT16, "div": 100},
    "avoided_cooling_ytd":    {"unit": "kWh", "PDO": 217, "CONV": ComfoNumConvs.UINT16},
    "avoided_cooling_total":  {"unit": "kWh", "PDO": 218, "CONV": ComfoNumConvs.UINT16},

**Comment by vekexasia** [comment]
it was closed by #64
