### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by mattapo** [vekexasia/comfoair-esp32#76]
Hi, i use  Esphome version 2024.6.6,

this error occurs during compilation:

"
.platformio\packages\toolchain-xtensa-esp32\xtensa-esp32-elf\include\c++\8.4.0\bitset: In member function 'void std::bitset<_Nb>::_M_copy_from_ptr(const _CharT*, std::size_t, std::size_t, std::size_t, _CharT, _CharT)':
src/esphome\components\comfoair\comfoair.h:14:18: error: expected unqualified-id before '(' token
 #define min(a,b) ((a) < (b) ? (a): (b))
                  ^
src/esphome\components\comfoair\comfoair.h:14:18: error: expected unqualified-id before '(' token
 #define min(a,b) ((a) < (b) ? (a): (b))
                  ^
src/esphome\components\comfoair\comfoair.h:14:18: error: expected unqualified-id before '(' token
 #define min(a,b) ((a) < (b) ? (a): (b))
"

Can you help me?

**Comment by vekexasia** [comment]
hey @mattapo let me give it a try and get back to u also u can join [discord](https://discord.gg/dUSSRezJXC) if you prefer a more instant response. most likely it's a bug I introduced previous days

**Comment by vekexasia** [comment]
can u show me your configuration?

**Comment by mattapo** [comment]
Any simple configuration, but also your example yaml.

**Comment by vekexasia** [comment]
If u can share your configuration (full) it would be better. Also first try with just comfoair:

**Comment by vekexasia** [comment]
@mattapo which version of esphome are u using?

**Comment by mattapo** [comment]
I'm using version 2024.6.6

**Comment by vekexasia** [comment]
can you try to:

1 have this minimal configuration:
```
comfoair:
  global_filters:
    - throttle: 10
```

NOTE: if you need to set **rx and tx** pins do that 

2. clean build files using either `esphome clean file.yaml` or by using the three dots in the interface like shown here:

![image](https://github.com/vekexasia/comfoair-esp32/assets/200523/38cff0c0-9516-4fd8-b630-f4e9560fa642)

and after that the error should go away as we found in discord with another user
