### ISSUE TITLE
missing file secrets.h

### ISSUE THREAD

**Issue by dumbo2** [vekexasia/comfoair-esp32#9]
I'm trying to compile the code but missing the file secrets.h. Can you help me

**Comment by svde** [comment]
#define MQTT_HOST "mqtt.fqdn.here"
#define MQTT_PASS ""
#define MQTT_PORT 1883
#define MQTT_PREFIX "comfoair"
#define MQTT_USER ""
#define WIFI_SSID "your-ssid"
#define WIFI_PASS "your-wifi-password"

**Comment by dumbo2** [comment]
Thanks

**Comment by svde** [comment]
Please close the issue.
